### ISSUE TITLE
How can disabled pressing enter to complete code?

### ISSUE THREAD

**Issue by amliuxin** [tushortz/vscode-Python-Extended#1]
this extension is easy to use, but tab for completion is enough, sometimes enter might make misoperation.

**Comment by tushortz** [comment]
@amliuxin 

On VScode, go to the `File` menu -> `Preferences` -> `Settings`.

In the `settings.json` file that is shown, search for `enter` and change the `editor.acceptSuggestionOnEnter` value to false and save.

![image](https://user-images.githubusercontent.com/13158672/27686532-15bca270-5ccb-11e7-8099-dbddc55a11ed.png)
