### ISSUE TITLE
Conflicts between Python extension and this one.

### ISSUE THREAD

**Issue by Shaddy** [tushortz/vscode-Python-Extended#2]
Snippets are only triggered if you don't write the module before. But if I backward and then write again, it gets recognized.

![python-extension-issue](https://user-images.githubusercontent.com/247221/28980471-246f47c4-794e-11e7-8ea2-8c5bc8dd5856.gif)

**Comment by tushortz** [comment]
I honk you should disable the snippet when not in use

**Comment by Shaddy** [comment]
what is that supposed to mean?

**Comment by tushortz** [comment]
Disable my extension when not really needed so that it doesn't conflict
with the other intellisense.

Mine is a snippet and it works differently from an actual intellisense

**Comment by Shaddy** [comment]
I appreciate your work, but it's pointless to have that dummy snippets why any kind of smart selection.

**Comment by tushortz** [comment]
You can make a fix for it and create a pull request and I'll merge it
