### ISSUE TITLE
Not working on class methods

### ISSUE THREAD

**Issue by baluyotraf** [tushortz/vscode-Python-Extended#3]
Before the issue, I just want to say that this is a great extension. I'm been looking for something like this in VS Code.

And for the issues, it doesn't seem to work on class methods or am I missing something here?

**Comment by tushortz** [comment]
No it doesn't work on class methods. There is a better extension by Don Jayamanne called **python**.
It works better than this but you need to do 
pip install pylint 
then enable pylint from vscode settings and you will be good to go 
null
