### ISSUE TITLE
Not working with Anaconda Python

### ISSUE THREAD

**Issue by ahmedhamdy2121** [tushortz/vscode-Python-Extended#4]
I tried it many times with Python, but it is not working.
What I expected it auto-write the function's parameters, but it is not.

**Comment by tushortz** [comment]
No it can't. It's a snippet.

Have a look at the python extension by Microsoft

**Comment by ahmedhamdy2121** [comment]
Yeah, I am working with Anaconda Python extension provided by MS of course, but your extension is a nice to have to auto-write the function's parameters.

**Comment by tushortz** [comment]
you can use pylance or the original python language server for vscode
