### ISSUE TITLE
Snippets with colon `:` should change to other character since it conflict with the character use in python

### ISSUE THREAD

**Issue by obayit** [tushortz/vscode-Python-Extended#8]
Every time I write a `for` loop or define a function, after I enter the colon `:`, vs code suggests these:
![Screenshot from 2021-07-25 16-22-09_001](https://user-images.githubusercontent.com/20386024/126902549-be9a7457-6675-41ff-987f-e2e879b403c5.png)

And of course when I press `enter` to make a new line, vs code writes the snippet instead 😢

Maybe replacing it with a semicolon `;` is better

**Comment by tushortz** [comment]
ok i see thanks. Can you test it to see if the changes fixes the issue
on your end?

**Comment by obayit** [comment]
Actually I don't know how to test this, but I think it is a straight forward and simple change.

**Comment by MarkSCQ** [comment]
I have the same issue, each time when I type ":" kind of intelligence will appear.
